version: '3'

services:
  db:
    image: linuxserver/mariadb
    command: mysqld --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - db:/config
    environment:
      - MYSQL_DATABASE=db
      - MYSQL_PASSWORD=nextcloud
      - MYSQL_ROOT_PASSWORD=nextcloud
      - MYSQL_USER=nextcloud

  app:
    image: nextcloud:apache
    restart: always
    ports:
      - 8080:80
    volumes:
      - nextcloud:/var/www/html
    environment:
      - MYSQL_DATABASE=db
      - MYSQL_HOST=db
      - MYSQL_PASSWORD=nextcloud
      - MYSQL_USER=nextcloud
    depends_on:
      - db

volumes:
  db:
  nextcloud:
