version: "3"

services:
  pihole:
    image: pihole/pihole:latest
    ports:
      - "443:443/tcp"
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
    environment:
      WEBPASSWORD: ${PASSWORD}
    volumes:
       - pihole:/etc/pihole/'
       - dnsmasq:/etc/dnsmasq.d/'
    dns:
      - 127.0.0.1
      - 1.1.1.1
    # Recommended but not required (DHCP needs NET_ADMIN)
    # https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN
    restart: always

volumes:
  pihole:
  dnsmasq:
